<?php
$helper = $this->helper('Idealpostcodes\Ukaddresssearch\Helper\Data'); ?>
<script type="text/javascript">
var api_key = "<?php echo $helper->getConfig('api_key'); ?>";
var postcodeLookup = <?php echo $helper->getConfig('postcodeLookup'); ?>;
var addressAutocomplete = <?php echo $helper->getConfig(
    'addressAutocomplete'
); ?>;
var populateOrganisation = <?php echo $helper->getConfig(
    'populateOrganisation'
); ?>;
var hoistCountryField = <?php echo $helper->getConfig('hoistCountryField'); ?>;
var requireCounty = <?php echo $helper->getConfig('requireCounty'); ?>;
var enabled = <?php echo $helper->getConfig('enabled'); ?>;

requirejs(['jquery'], function(jQuery){
  jQuery(function() {
    // Exit early if disabled
    if (enabled === false) return;

    window.idpc = {
      shippingFormBinding: new IdpcBinding({
        container: '#checkout-step-shipping',
        api_key: api_key,
        postcodeLookup: postcodeLookup,
        requireCounty: requireCounty,
        addressAutocomplete: addressAutocomplete,
        populateOrganisation: populateOrganisation,
        hoistCountryField: hoistCountryField,
        jQuery: jQuery
      }),

      billingFormBinding: new IdpcBinding({
        container: '.payment-method-billing-address',
        api_key: api_key,
        postcodeLookup: postcodeLookup,
        requireCounty: requireCounty,
        addressAutocomplete: addressAutocomplete,
        populateOrganisation: populateOrganisation,
        hoistCountryField: hoistCountryField,
        jQuery: jQuery
      })
    }
  });
});
</script>

