<?php
$helper = $this->helper('Idealpostcodes\Ukaddresssearch\Helper\Data'); ?>

<script type="text/javascript">
requirejs(['jquery'], function(jQuery){
  jQuery(function() {
    var api_key = "<?php echo $helper->getConfig('api_key'); ?>";
    var postcodeLookup = <?php echo $helper->getConfig('postcodeLookup'); ?>;
    var addressAutocomplete = <?php echo $helper->getConfig(
      'addressAutocomplete'
    ); ?>;
    var populateOrganisation = <?php echo $helper->getConfig(
      'populateOrganisation'
    ); ?>;
    var hoistCountryField = <?php echo $helper->getConfig('hoistCountryField'); ?>;
    var requireCounty = <?php echo $helper->getConfig('requireCounty'); ?>;
    var enabled = <?php echo $helper->getConfig('enabled'); ?>;
    var targets = "<?php echo $helper->getConfig('multishipping_checkout_register_target'); ?>";

    // Exit early if disabled
    if (enabled === false) return;

    window.idpc = new IdpcWatcher({
      targets: targets,
      options: {
        api_key: api_key,
        postcodeLookup: postcodeLookup,
        requireCounty: requireCounty,
        addressAutocomplete: addressAutocomplete,
        populateOrganisation: populateOrganisation,
        hoistCountryField: hoistCountryField,
        jQuery: jQuery,
        lineOneIdentifier: "#street_1",
        lineTwoIdentifier: "#street_2",
        lineThreeIdentifier: "#street_3",
        organisationIdentifier: "#company",
        postTownIdentifier: "#city",
        countyIdentifier: "#region",
        countryIdentifier: "#country",
        addressLinesIdentifier: "div.field.street"
      }
    });
  });
});
</script>
