<?php
$helper = $this->helper('Idealpostcodes\Ukaddresssearch\Helper\Data'); ?>

<script type="text/javascript">
requirejs(['jquery'], function(jQuery){
  jQuery(function() {
    var apiKey = "<?php echo $helper->getConfig('api_key'); ?>";
    var postcodeLookup = <?php echo $helper->getConfig('postcodeLookup'); ?>;
    var autocomplete = <?php echo $helper->getConfig('addressAutocomplete'); ?>;
    var populateOrganisation = <?php echo $helper->getConfig(
        'populateOrganisation'
    ); ?>;
    var hoistCountry = <?php echo $helper->getConfig('hoistCountryField'); ?>;
    var populateCounty = <?php echo $helper->getConfig('requireCounty'); ?>;
    var enabled = <?php echo $helper->getConfig('enabled'); ?>;
    console.log("enabled", enabled);
    // Exit early if disabled
    if (enabled === false) return;
    window.idpcConfig = {
      apiKey: apiKey,
      postcodeLookup: postcodeLookup,
      autocomplete: autocomplete,
      populateCounty: populateCounty,
      populateOrganisation: populateOrganisation,
      hoistCountry: hoistCountry,
    }
    window.idpcStart();
  });
});
</script>
