version: "3.0"
services:
  db:
    image: library/mariadb:10.2-bionic
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - ./docker/.env
  es:
    image: library/elasticsearch:7.0.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  web:
    depends_on:
      - es
    build:
      context: "."
      args:
        BASE_IMAGE: idealpostcodes/magento-test:m2.4-php7.4
