#!/usr/bin/env bash

su www-data <<EOSU
set -e

mysql -u magento -pmagento -D magento -e 'UPDATE `core_config_data` SET `value` = "http://127.0.0.1/" WHERE `core_config_data`.`path` = "web/secure/base_url"'
EOSU
