<?php /** @var Magento\Framework\View\TemplateEngine\Php $this */
$helper = $this->helper('Idealpostcodes\Ukaddresssearch\Helper\Data');
?>
<?php if(!isset($secureRenderer)) { ?>
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {
        var apiKey = "<?= $block->escapeJsQuote($helper->getAdminConfig('api_key')) ?>";
        var autocomplete = <?= $block->escapeJs($helper->getAdminConfig('addressAutocomplete')) ?>;
        var removeOrganisation = <?= $block->escapeJs($helper->getAdminConfig('removeOrganisation')) ?>;
        var populateCounty = <?= $block->escapeJs($helper->getAdminConfig('requireCounty')) ?>;
        var enabled = <?= $block->escapeJs($helper->getAdminConfig('enabled')) ?>;
        var customFields = <?= $block->escapeJs(trim(preg_replace("/\r|\n/", "", $helper->getAdminConfig('customFields')))) ?>;
        // Exit early if disabled
        if (enabled === false) return;
        window.idpcConfig = {
            apiKey: apiKey,
            postcodeLookup: false,
            autocomplete: autocomplete,
            populateCounty: populateCounty,
            removeOrganisation: removeOrganisation,
            hoistCountry: false,
            customFields: customFields
        };
        window.idpcStart();
        });
    </script>
<?php } else {
    echo $secureRenderer->renderTag('script', [], '
        document.addEventListener("DOMContentLoaded", function() {
          var apiKey = "' . $block->escapeJsQuote($helper->getAdminConfig('api_key')) . '";
          var autocomplete = ' . $block->escapeJs($helper->getAdminConfig('addressAutocomplete')) . ';
          var removeOrganisation = ' . $block->escapeJs($helper->getAdminConfig('removeOrganisation')) . ';
          var populateCounty = ' . $block->escapeJs($helper->getAdminConfig('requireCounty')) . ';
          var enabled = ' . $block->escapeJs($helper->getAdminConfig('enabled')) . ';
          var customFields = ' . $block->escapeJs(trim(preg_replace("/\r|\n/", "", $helper->getAdminConfig('customFields')))) . ';
          // Exit early if disabled
          if (enabled === false) return;
          window.idpcConfig = {
            apiKey: apiKey,
            postcodeLookup: false,
            autocomplete: autocomplete,
            populateCounty: populateCounty,
            removeOrganisation: removeOrganisation,
            hoistCountry: false,
            customFields: customFields
          };
          window.idpcStart();
        });
    ', false);
}
?>
