<?php /** @var Magento\Framework\View\TemplateEngine\Php $this */
$helper = $this->helper('Idealpostcodes\Ukaddresssearch\Helper\Data');

$script = '
document.addEventListener(\'DOMContentLoaded\', function() {
  var apiKey = "' . $helper->getConfig('api_key') . '";
  var autocomplete = ' . $helper->getConfig('addressAutocomplete') . ';
  var populateOrganisation = ' . $helper->getConfig('populateOrganisation') . ';
  var populateCounty = ' . $helper->getConfig('requireCounty') . ';
  var enabled = ' . $helper->getConfig('enabled') . ';
  var customFields = ' . trim(preg_replace("/\r|\n/", "", $helper->getConfig('customFields'))) . ';
  // Exit early if disabled
  if (enabled === false) return;
  window.idpcConfig = {
    apiKey: apiKey,
    postcodeLookup: false,
    autocomplete: autocomplete,
    populateCounty: populateCounty,
    populateOrganisation: populateOrganisation,
    hoistCountry: false,
    customFields: customFields
  };
  window.idpcStart();
});
';

$secureRenderer->renderTag('script', [], $script, false);
?>
