name: Magento 2.4.6 CI with PHP 8.2

on:
  - push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Launch Magento test environment
        env:
          PHP: "82"
          COMPOSE_INTERACTIVE_NO_CLI: "1"
        run: make up

      - uses: cypress-io/github-action@v2
        with:
          project: ./test/e2e
          config: baseUrl=http://localhost:3000
        env:
          CYPRESS_API_KEY: ${{ secrets.API_KEY }}
          CYPRESS_MAGENTO_VERSION: "2.4"
